server:
  port: ${PORT:${SERVER_PORT:0}}  # Puerto en el que se ejecutará el servidor, con un valor predeterminado de 0 si no se proporciona

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2 # Version de base de dato embebida Mongo
    data:
      mongodb:
        database: test # Nombre de la base de datos
        port: 27017 # Puerto de base de datos
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
queue:
  name: mensajesQueue

# Configuración de Eureka
eureka:

  client:
    service-url:
      default-zone: http://localhost:8761/eureka # URL predeterminada del servicio de registro Eureka
    # Habilita el registro y la recuperación de instancias con Eureka
    register-with-eureka: true
    fetch-registry: true
    # Intervalo de tiempo para recuperar el registro de Eureka
    registry-fetch-interval-seconds: 5
    # Habilita la comprobación de salud de la instancia con Eureka
    healthcheck:
      enabled: true

  instance:
    # ID único de la instancia, con un valor predeterminado basado en el nombre de la aplicación y un identificador aleatorio
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Indica que se prefiere la dirección IP al registrar la instancia con Eureka
    prefer-ip-address: true
    # Intervalo de renovación de arrendamiento con Eureka
    lease-renewal-interval-in-seconds: 5
    # Duración de expiración del arrendamiento con Eureka
    lease-expiration-duration-in-seconds: 10

management:
  metrics:
    export:
      simple: # Esta línea deshabilita la exportación de métricas al sistema de métricas simple interno de Spring Boot.
        enabled: false
      prometheus:
        enabled: true # Esta línea habilita la exportación de métricas a Prometheus, un sistema de monitoreo y alerta para aplicaciones.
                      #  Prometheus es ampliamente usado para capturar métricas en tiempo real y proporcionar insights sobre el rendimiento y salud de las aplicaciones en entornos de producción.
  tracing:
    sampling:
      probability: 1.0 # Configuración de la probabilidad de muestreo de trazas
