server:
  port: 8080 # Puerto en el que se ejecutará el servidor

spring:
  application:
    name: gateway
  cloud:
    gateway:
     # Habilita la integración con el descubrimiento de servicios mediante Eureka
      discovery:
        locator:
          enabled: true
      # Configuración de las rutas del gateway
      routes:
         # Configuración de una ruta para el servicio de catálogo
        - id: catalogRoute
          # URI de la instancia balanceada del servicio de catálogo
          uri: lb://CATALOG-SERVICE
           # Predicados para enrutar solicitudes al servicio de catálogo basadas en la ruta
          predicates:
            - Path=/catalog/**
     

# Configuración de Eureka
eureka:
  client:
   # Habilita el registro y la recuperación de instancias con Eureka
    register-with-eureka: true
    fetch-registry: true
    # Intervalo de tiempo para recuperar el registro de Eureka
    registry-fetch-interval-seconds: 5
    # Habilita la comprobación de salud de la instancia con Eureka
    healthcheck:
      enabled: true
     # URL predeterminada del servicio de registro Eureka
    service-url:
      default-zone: http://localhost:8761/eureka
      
  instance:
    # ID único de la instancia, con un valor predeterminado basado en el nombre de la aplicación y un identificador aleatorio
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Indica que se prefiere la dirección IP al registrar la instancia con Eureka   
    prefer-ip-address: true
      # Intervalo de renovación de arrendamiento con Eureka
    lease-renewal-interval-in-seconds: 5
    # Duración de expiración del arrendamiento con Eureka
    lease-expiration-duration-in-seconds: 10
